import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..', '..');
const inputPath = path.join(repoRoot, 'data', 'cards.ts');
const outputPath = path.join(repoRoot, 'switch-port', 'source', 'card_data.cpp');
const source = fs.readFileSync(inputPath, 'utf8');

const cardPattern = /\{\s*id:\s*(\d+),\s*name:\s*"([^"]*)",\s*year:\s*(-?\d+),\s*imageUrl:\s*"[^"]*",\s*bibleRef:\s*"([^"]*)"\s*\}/g;
const cards = [];
for (const match of source.matchAll(cardPattern)) {
  cards.push({
    id: Number(match[1]),
    name: match[2],
    year: match[3],
    bibleRef: match[4],
  });
}

if (cards.length !== 112) {
  throw new Error(`Se esperaban 112 cartas y se encontraron ${cards.length}`);
}

const cppString = (value) => `u8"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
const rows = cards.map((card) =>
  `    {${card.id}, ${cppString(card.name)}, ${card.year}LL, ${cppString(card.bibleRef)}},`
).join('\n');

const output = `// Generated from data/cards.ts by tools/generate_card_data.mjs.
// Do not edit this file by hand.
#include "card_data.hpp"

#include <algorithm>

namespace jwtl {
namespace {

const std::vector<Card> kCards = {
${rows}
};

const std::vector<DeckDefinition> kDecks = {
    {"complete", "Biblia completa", "Los 112 acontecimientos"},
    {"old_testament", "Antiguo Testamento", "Antes del nacimiento de Jesus"},
    {"new_testament", "Nuevo Testamento", "Jesus y los primeros cristianos"},
    {"patriarchs", "Los patriarcas", "Desde Adan hasta Moises"},
    {"kings", "Reyes y profetas", "Los reinos de Israel y Juda"},
    {"jesus", "Vida de Jesus", "Nacimiento, ministerio y resurreccion"},
    {"early_church", "Iglesia primitiva", "Los apostoles y la congregacion"},
    {"creation", "Creacion y Diluvio", "Los primeros dias de la humanidad"},
    {"exile", "Exilio y regreso", "Babilonia y la vuelta a Jerusalen"},
};

}  // namespace

const std::vector<Card>& allCards() {
    return kCards;
}

const Card* findCard(int id) {
    if (id < 1 || id > static_cast<int>(kCards.size())) {
        return nullptr;
    }
    const Card& candidate = kCards[static_cast<std::size_t>(id - 1)];
    return candidate.id == id ? &candidate : nullptr;
}

const std::vector<DeckDefinition>& deckDefinitions() {
    return kDecks;
}

std::vector<int> cardIdsForDeck(const std::string& deckId) {
    std::vector<int> ids;
    ids.reserve(kCards.size());
    for (const Card& card : kCards) {
        bool include = false;
        if (deckId == "complete") include = true;
        else if (deckId == "old_testament") include = card.year < 0;
        else if (deckId == "new_testament") include = card.year >= 0;
        else if (deckId == "patriarchs") include = card.year < -1593 && card.year >= -4026;
        else if (deckId == "kings") include = card.year >= -1117 && card.year < -539;
        else if (deckId == "jesus") include = card.year >= -2 && card.year <= 33;
        else if (deckId == "early_church") include = card.year > 33 && card.year <= 100;
        else if (deckId == "creation") include = card.year <= -2370 && card.year >= -14000000000LL;
        else if (deckId == "exile") include = card.year >= -625 && card.year <= -406;
        if (include) ids.push_back(card.id);
    }
    return ids;
}

}  // namespace jwtl
`;

fs.writeFileSync(outputPath, output);
console.log(`Generadas ${cards.length} cartas en ${path.relative(repoRoot, outputPath)}`);
