// Generated from data/cards.ts by tools/generate_card_data.mjs.
// Do not edit this file by hand.
#include "card_data.hpp"

#include <algorithm>

namespace jwtl {
namespace {

const std::vector<Card> kCards = {
    {1, u8"Creación del Universo", -14000000000LL, u8"Génesis 1:1"},
    {2, u8"Creación de Adán", -4026LL, u8"Génesis 2:7"},
    {3, u8"Primera profecía", -4025LL, u8"Génesis 3:15"},
    {4, u8"Caín mata a Abel", -3896LL, u8"Génesis 4:8"},
    {5, u8"Nace el justo Enoc", -3403LL, u8"Génesis 5:18"},
    {6, u8"Nace Matusalén", -3338LL, u8"Génesis 5:21"},
    {7, u8"Nace Lamec", -3151LL, u8"Génesis 5:25"},
    {8, u8"Muerte de Adán con 930 años", -3096LL, u8"Génesis 5:5"},
    {9, u8"Traslación de Enoc", -3038LL, u8"Génesis 5:24"},
    {10, u8"Nace Noé", -2970LL, u8"Génesis 5:28-29"},
    {11, u8"Jehová decreta el Diluvio", -2490LL, u8"Génesis 6:3, 13"},
    {12, u8"Nace Sem", -2468LL, u8"Génesis 5:32"},
    {13, u8"Noé comienza a construir el arca", -2420LL, u8"Génesis 6:14-16"},
    {14, u8"Fallece Lamec", -2375LL, u8"Génesis 5:31"},
    {15, u8"Fallece Matusalén con 969 años", -2370LL, u8"Génesis 5:27"},
    {16, u8"Comienza el Diluvio", -2370LL, u8"Génesis 7:11"},
    {17, u8"Construcción de la Torre de Babel", -2239LL, u8"Génesis 11:1-9"},
    {18, u8"Muere Noé con 950 años", -2020LL, u8"Génesis 9:29"},
    {19, u8"Nace Abrahán", -2018LL, u8"Génesis 11:26"},
    {20, u8"Establecimiento del pacto abrahámico", -1943LL, u8"Génesis 12:1-3"},
    {21, u8"Abrahán rescata a su sobrino Lot", -1933LL, u8"Génesis 14:14-16"},
    {22, u8"Nacimiento de Ismael", -1932LL, u8"Génesis 16:15-16"},
    {23, u8"Se hace el pacto de la circuncisión", -1919LL, u8"Génesis 17:9-14"},
    {24, u8"Destrucción de Sodoma y Gomorra", -1919LL, u8"Génesis 19:24-25"},
    {25, u8"Nacimiento de Isaac", -1918LL, u8"Génesis 21:2-3"},
    {26, u8"Ismael y su madre son despedidos", -1913LL, u8"Génesis 21:14"},
    {27, u8"Isaac es ofrecido en Moria", -1893LL, u8"Génesis 22:1-12"},
    {28, u8"Muere Sara con 127 años", -1881LL, u8"Génesis 23:1-2"},
    {29, u8"Isaac se casa con Rebeca", -1878LL, u8"Génesis 24:67"},
    {30, u8"Fallece Sem con 600 años", -1868LL, u8"Génesis 11:10-11"},
    {31, u8"Nacimiento de Esaú y Jacob", -1858LL, u8"Génesis 25:24-26"},
    {32, u8"Muere Abrahán con 175 años", -1843LL, u8"Génesis 25:7-8"},
    {33, u8"Esaú se casa con Judit", -1818LL, u8"Génesis 26:34"},
    {34, u8"Ismael fallece con 137 años", -1795LL, u8"Génesis 25:17"},
    {35, u8"Jacob huye a Padán-aram", -1781LL, u8"Génesis 28:2-5"},
    {36, u8"Jacob se casa con Lea y Raquel", -1774LL, u8"Génesis 29:23-28"},
    {37, u8"Nacimiento de José", -1767LL, u8"Génesis 30:22-24"},
    {38, u8"Jacob regresa a Canaán", -1761LL, u8"Génesis 31:17-18"},
    {39, u8"La lucha de Jacob con el ángel", -1761LL, u8"Génesis 32:24-28"},
    {40, u8"Venden a José como esclavo", -1750LL, u8"Génesis 37:28"},
    {41, u8"Muere Isaac con 180 años", -1739LL, u8"Génesis 35:28-29"},
    {42, u8"José se convierte en virrey de Egipto", -1737LL, u8"Génesis 41:40-43"},
    {43, u8"Jacob se traslada a Egipto", -1728LL, u8"Génesis 46:5-7"},
    {44, u8"Fallece Jacob con 147 años", -1712LL, u8"Génesis 47:28"},
    {45, u8"Muere José con 110 años", -1657LL, u8"Génesis 50:26"},
    {46, u8"Pruebas de Job", -1613LL, u8"Job 1:1-22"},
    {47, u8"Nace Moisés", -1593LL, u8"Éxodo 2:1-2"},
    {48, u8"Moisés huye a Madián", -1553LL, u8"Éxodo 2:15"},
    {49, u8"La zarza ardiente", -1514LL, u8"Éxodo 3:2-4"},
    {50, u8"Éxodo de Egipto", -1513LL, u8"Éxodo 12:40-41"},
    {51, u8"Los Diez Mandamientos", -1513LL, u8"Éxodo 20:1-17"},
    {52, u8"Se completa el tabernáculo", -1512LL, u8"Éxodo 40:17, 33-34"},
    {53, u8"Israel entra en Canaán", -1473LL, u8"Josué 3:14-17"},
    {54, u8"Moisés muere en Moab con 120 años", -1473LL, u8"Deuteronomio 34:5-7"},
    {55, u8"Distribución de Canaán", -1467LL, u8"Josué 14:1-5"},
    {56, u8"Fallece Josué con 110 años", -1450LL, u8"Josué 24:29"},
    {57, u8"Rut se casa con Boaz", -1400LL, u8"Rut 4:13"},
    {58, u8"Nace Ana", -1300LL, u8"1 Samuel 1:2"},
    {59, u8"Nace Samuel", -1192LL, u8"1 Samuel 1:20"},
    {60, u8"Victoria de Jefté sobre Ammón", -1173LL, u8"Jueces 11:32-33"},
    {61, u8"El arca se muda de Silo", -1137LL, u8"1 Samuel 4:1-11"},
    {62, u8"Nace Jonatán, hijo de Saúl", -1137LL, u8"1 Samuel 14:49"},
    {63, u8"Se nombra rey a Saúl", -1117LL, u8"1 Samuel 10:24"},
    {64, u8"David nace en Belén", -1107LL, u8"1 Samuel 16:1, 11-13"},
    {65, u8"Abigail se casa con David", -1100LL, u8"1 Samuel 25:42"},
    {66, u8"Samuel unge a David como rey", -1097LL, u8"1 Samuel 16:13"},
    {67, u8"Muerte del rey Saúl", -1077LL, u8"1 Samuel 31:4-6"},
    {68, u8"David ungido como rey de Judá", -1077LL, u8"2 Samuel 2:4"},
    {69, u8"Dios le hace a David la promesa del Reino", -1070LL, u8"2 Samuel 7:12-16"},
    {70, u8"David toma Jerusalén y la hace capital", -1070LL, u8"2 Samuel 5:6-9"},
    {71, u8"Fallece David con 70 años", -1037LL, u8"1 Reyes 2:10-11"},
    {72, u8"Salomón comienza a reinar", -1037LL, u8"1 Reyes 1:39"},
    {73, u8"Comienzo de la construcción del templo", -1034LL, u8"1 Reyes 6:1"},
    {74, u8"Se termina el templo de Jerusalén", -1027LL, u8"1 Reyes 6:38"},
    {75, u8"Reino dividido: Israel y Judá", -997LL, u8"1 Reyes 12:16-20"},
    {76, u8"Elías desafía a los profetas de Baal", -930LL, u8"1 Reyes 18:20-40"},
    {77, u8"Josías promueve la adoración pura", -659LL, u8"2 Reyes 22:1-2"},
    {78, u8"Nace Ezequiel", -643LL, u8"Ezequiel 1:3"},
    {79, u8"Nabucodonosor derrota al ejército egipcio", -625LL, u8"Jeremías 46:2"},
    {80, u8"Ezequiel es llevado cautivo a Babilonia", -617LL, u8"Ezequiel 1:1-2"},
    {81, u8"Ezequiel comienza a profetizar", -613LL, u8"Ezequiel 1:3"},
    {82, u8"Nabucodonosor destruye Jerusalén", -607LL, u8"2 Reyes 25:8-10"},
    {83, u8"Ciro conquista Babilonia", -539LL, u8"Daniel 5:30-31"},
    {84, u8"Los judíos exiliados regresan a Jerusalén", -537LL, u8"Esdras 1:1-4"},
    {85, u8"Ester salva a los judíos", -480LL, u8"Ester 7:1-6"},
    {86, u8"Se reconstruyen los muros de Jerusalén", -455LL, u8"Nehemías 2:17-18"},
    {87, u8"Jerusalem completamente reconstruida", -406LL, u8"Nehemías 6:15"},
    {88, u8"Renovación del templo tras idolatría griega", -165LL, u8"Daniel 11:31-32"},
    {89, u8"Herodes toma Jerusalén por asalto", -37LL, u8"Mateo 2:1"},
    {90, u8"Herodes reconstruye el tercer templo", -17LL, u8"Juan 2:20"},
    {91, u8"José se casa con María", -2LL, u8"Mateo 1:24"},
    {92, u8"Nacimiento de Jesús", -2LL, u8"Lucas 2:6-7"},
    {93, u8"Bautismo de Jesús", 29LL, u8"Mateo 3:13-17"},
    {94, u8"Jesús elige a los doce apóstoles", 31LL, u8"Lucas 6:13-16"},
    {95, u8"Jesús pronuncia el Sermón del Monte", 31LL, u8"Mateo 5:1-2"},
    {96, u8"Jesús resucita a Lázaro", 32LL, u8"Juan 11:43-44"},
    {97, u8"Juan el Bautista es decapitado", 32LL, u8"Mateo 14:10"},
    {98, u8"Santiago y Juan: Hijos del Trueno", 33LL, u8"Marcos 3:17"},
    {99, u8"Jehová derrama espíritu santo", 33LL, u8"Hechos 2:1-4"},
    {100, u8"Jesús muere en el madero", 33LL, u8"Lucas 23:46"},
    {101, u8"Resurrección de Jesús", 33LL, u8"Mateo 28:5-6"},
    {102, u8"Cornelio se convierte al cristianismo", 36LL, u8"Hechos 10:44-48"},
    {103, u8"Pablo inicia su primer viaje misional", 47LL, u8"Hechos 13:2-4"},
    {104, u8"Cuerpo gobernante rige contra la circuncisión", 49LL, u8"Hechos 15:28-29"},
    {105, u8"Pablo inicia su segundo viaje misional", 49LL, u8"Hechos 15:40"},
    {106, u8"Pablo inicia su tercer viaje misional", 52LL, u8"Hechos 18:23"},
    {107, u8"Rebelión judía contra Roma", 66LL, u8"Lucas 21:20"},
    {108, u8"Los romanos destruyen Jerusalén", 70LL, u8"Mateo 24:1-2"},
    {109, u8"Muere Juan, el último apóstol", 100LL, u8"Juan 21:22-23"},
    {110, u8"Jesús pregunta en el templo", 12LL, u8"Lucas 2:46-47"},
    {111, u8"Joaquín se rinde ante Nabucodonosor", -617LL, u8"2 Reyes 24:12"},
    {112, u8"Visita de los astrólogos", -1LL, u8"Mateo 2:1-2"},
};

const std::vector<DeckDefinition> kDecks = {
    {"complete", "Biblia completa", "Los 112 acontecimientos"},
    {"old_testament", "Antiguo Testamento", "Antes del nacimiento de Jesus"},
    {"new_testament", "Nuevo Testamento", "Jesus y los primeros cristianos"},
    {"patriarchs", "Los patriarcas", "Desde Adan hasta Moises"},
    {"kings", "Reyes y profetas", "Los reinos de Israel y Juda"},
    {"jesus", "Vida de Jesus", "Nacimiento, ministerio y resurreccion"},
    {"early_church", "Iglesia primitiva", "Los apostoles y la congregacion"},
    {"creation", "Creacion y Diluvio", "Los primeros dias de la humanidad"},
    {"exile", "Exilio y regreso", "Babilonia y la vuelta a Jerusalen"},
};

}  // namespace

const std::vector<Card>& allCards() {
    return kCards;
}

const Card* findCard(int id) {
    if (id < 1 || id > static_cast<int>(kCards.size())) {
        return nullptr;
    }
    const Card& candidate = kCards[static_cast<std::size_t>(id - 1)];
    return candidate.id == id ? &candidate : nullptr;
}

const std::vector<DeckDefinition>& deckDefinitions() {
    return kDecks;
}

std::vector<int> cardIdsForDeck(const std::string& deckId) {
    std::vector<int> ids;
    ids.reserve(kCards.size());
    for (const Card& card : kCards) {
        bool include = false;
        if (deckId == "complete") include = true;
        else if (deckId == "old_testament") include = card.year < 0;
        else if (deckId == "new_testament") include = card.year >= 0;
        else if (deckId == "patriarchs") include = card.year < -1593 && card.year >= -4026;
        else if (deckId == "kings") include = card.year >= -1117 && card.year < -539;
        else if (deckId == "jesus") include = card.year >= -2 && card.year <= 33;
        else if (deckId == "early_church") include = card.year > 33 && card.year <= 100;
        else if (deckId == "creation") include = card.year <= -2370 && card.year >= -14000000000LL;
        else if (deckId == "exile") include = card.year >= -625 && card.year <= -406;
        if (include) ids.push_back(card.id);
    }
    return ids;
}

}  // namespace jwtl
